services:
  frontend:
    build: ./frontend
    ports:
      - 5076:8080
    depends_on:
      - backend
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      postgis:
        condition: service_healthy
  postgis:
    image: postgis/postgis
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
